version: '3'
services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    container_name: client-docker
    restart: always
    links:
      - server
  server:
    build: ./server
    ports:
      - "3000:3000"
    container_name: server-docker
    restart: always
    environment:
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGHOST=host.docker.internal
      - PGDATABASE=urban_sky
      - PGPORT=5432
    links:
      - db
  db:
    image: postgres:11.6-alpine
    ports:
    - "5432:5432"
    container_name: database-docker
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=urban_sky